# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94dbea0ebb49b94632e3f9862466965bd3d47e8cc2845e9a123942a792423a47b3db38c47931cb5e8382c6403ec8f59b45fa8afc3eedd058a7f88e077f36f489

test:
  secret_key_base: 7373b29899728c4f6643f88c0413653d5f9a64211a6f6e35f6ea6ec611aa04a17853c4dfac41656ed29bce39588512579ab3e0dfde3bd1a8be84bdcb7957cfcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
